system:
  certificateFilePath: /tmp/certs/thingCert.crt
  privateKeyPath: /tmp/certs/privKey.key
  rootCaPath: /tmp/certs/rootCA.pem
  rootpath: /greengrass/v2
  thingName: test1-local
services:
  aws.greengrass.Nucleus:
    componentType: NUCLEUS
    configuration:
      awsRegion: eu-west-1
      componentStoreMaxSizeBytes: 10000000000
      deploymentPollingFrequencySeconds: 15
      httpClient: {}
      iotCredEndpoint: c26jl1p6qg1otw.credentials.iot.eu-west-1.amazonaws.com
      iotDataEndpoint: acwprzq1nws9h-ats.iot.eu-west-1.amazonaws.com
      iotRoleAlias: GreengrassV2TokenExchangeRoleAlias
      jvmOptions: -Dlog.store=FILE
      logging: {}
      networkProxy:
        proxy: {}
      platformOverride: {}
      runWithDefault:
        posixUser: ggc_user:ggc_group
    dependencies: []
    lifecycle:
      bootstrap:
        requiresPrivilege: true
        script: >-
          
          set -eu

          KERNEL_ROOT="/greengrass/v2"

          UNPACK_DIR="/greengrass/v2/packages/artifacts-unarchived/aws.greengrass.Nucleus/2.5.3/aws.greengrass.nucleus"

          rm -r "$KERNEL_ROOT"/alts/current/*

          echo "-Dlog.store=FILE" > "$KERNEL_ROOT/alts/current/launch.params"

          ln -sf "$UNPACK_DIR" "$KERNEL_ROOT/alts/current/distro"

          exit 100
    version: 2.5.3
  main:
    dependencies:
      - aws.greengrass.Nucleus
      - aws.greengrass.Nucleus
    lifecycle: {}
